version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      development-tools:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      development-tools:
        dependency-type: development
        update-types:
          - minor
          - patch
